### ISSUE TITLE
Using importFromPlugin() for tomo.

### ISSUE THREAD

**Issue by dmaluenda** [scipion-em/scipion-em-eman2#42]
Scipion has a [function to import python objects from other plugins](https://github.com/I2PC/scipion/blob/d1a60f69960d1079bbbecde5bf3f5f4017b36927/pyworkflow/utils/utils.py#L772-L788). This functions skips the error raising when plugin is not found and [gives a common hint](https://github.com/I2PC/scipion/blob/d1a60f69960d1079bbbecde5bf3f5f4017b36927/pyworkflow/utils/utils.py#L732-L769) to help user how to solve the dependency.

I suggest to import the eman-tomo protocols without the try in the [protocols/__init__.py](https://github.com/scipion-em/scipion-em-eman2/blob/b99c87ef5675dbf681cc1d0d0d7dc7293371fcb5/eman2/protocols/__init__.py#L39-L48) and import the `scipion-em-tomo`'s objects using the that functions. For instance, for the [protocol_tomo_boxing](https://github.com/scipion-em/scipion-em-eman2/blob/b99c87ef5675dbf681cc1d0d0d7dc7293371fcb5/eman2/protocols/protocol_tomo_boxing.py#L37-L38) I would import as follow
```
from pyworkflow.utils import importFromPlugin
ProtTomoPicking = importFromPlugin("tomo.protocols", "ProtTomoPicking", errorMsg=tomoNeededMsg)
SetOfCoordinates3D = importFromPlugin("tomo.objects", "SetOfCoordinates3D", errorMsg=tomoNeededMsg)
```
where
```
tomoNeededMsg='To use a Tomography protocol scipion-em-tomo plugin is required.' 
              ' See https://github.com/scipion-em/scipion-em-tomo for further details'
```
is a common message defined in constants or wherever.

Alternatively, if this solutions seems tedious, it can be done in the init.py at once but using the `pluginNotFound()` function in order to print the Scipion's hint of how to install plugins
```
try:
    from protocol_tomo_boxing import EmanProtTomoBoxing
    ....
except ImportError:
    from pyworkflow.utils import pluginNotFound
    pluginNotFound("tomo", errorMsg='To use a Tomography protocol scipion-em-tomo plugin is required.'
                                    ' See https://github.com/scipion-em/scipion-em-tomo for further details')
```

In addition, I would not raise an error in any case in order to prevent make eman inaccessible for those users that hasn't scipion-em-tomo installed.

**Comment by adrianq** [comment]
@dmaluenda  We were already using your second proposal (see https://github.com/scipion-em/scipion-em-eman2/blob/fix/initialmodel_subtomo_ref_fixes/eman2/protocols/__init__.py#L46). It is in a PR that is about to be merged to the tomo branch. Anyway, I find you first proposal a bit more elegant so I will change it before merging. Thanks for keeping an eye on this!
