### ISSUE TITLE
We are searching for e2proc2d.py script in the wrong place

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-eman2#7]
00284:   /home/josem/work/development/scipion/software/em/eman-2.21/bin/e2proc2d.py  Runs/004705_ProtMotionCorr/extra/14sep05c_c_00003gr_00014sq_00011hl_00004es.frames_aligned_mic.mrc Runs/004705_ProtMotionCorr/extra/14sep05c_c_00003gr_00014sq_00011hl_00004es.frames_thumbnail.png --fouriershrink 6 --process normalize
00285:   /bin/sh: 1: /home/josem/work/development/scipion/software/em/eman-2.21/bin/e2proc2d.py: not found
00286:   ERROR: Movie  failed

**Comment by azazellochg** [comment]
I thought I fixed it in devel-pluginization(-fixes?), maybe not. Thanks!

**Comment by azazellochg** [comment]
@delarosatrevin the path seems to be correct, what are you running?

**Comment by delarosatrevin** [comment]
Yes, it seems correct! I'm closing this issue.
