### ISSUE TITLE
Refine test is failing with 2.91

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-eman2#96]
Hi!

Buildbot is failing. Locally it is failing too:
00025:   Traceback (most recent call last):
00026:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 200, in run
00027:       self._run()
00028:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 251, in _run
00029:       resultFiles = self._runFunc()
00030:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 247, in _runFunc
00031:       return self._func(*self._args)
00032:     File "/home/pablo/desarrollo/scipion-em-eman2/eman2/protocols/protocol_refineasy.py", line 326, in createOutputStep
00033:       self._fillDataFromIter(newPartSet, iterN)
00034:     File "/home/pablo/desarrollo/scipion-em-eman2/eman2/protocols/protocol_refineasy.py", line 524, in _fillDataFromIter
00035:       imgSet.copyItems(partIter,
00036:     File "/home/pablo/desarrollo/scipion-em/pwem/objects/data.py", line 933, in copyItems
00037:       row = None if itemDataIter is None else next(itemDataIter)
00038:     File "/home/pablo/desarrollo/scipion-em-eman2/eman2/protocols/protocol_refineasy.py", line 467, in _iterTextFile
00039:       with open(self._getFileName('angles', iter=iterN)) as f:
00040:   FileNotFoundError: [Errno 2] No such file or directory: 'Runs/000128_EmanProtRefine/extra/projectionAngles_it01.txt'
00041:   Protocol failed: [Errno 2] No such file or directory: 'Runs/000128_EmanProtRefine/extra/projectionAngles_it01.txt'

Error in buildbot might be related but is not exactly the same.

I do not have that Runs/000128_EmanProtRefine/extra/projectionAngles_it01.txt.

My extra folder looks like:
![image](https://user-images.githubusercontent.com/785633/110957060-8dd0f680-834b-11eb-8f25-29fea9b31351.png)

Eman refine seems to have finished correctly. Same in buildbot.

**Comment by pconesa** [comment]
Yep

**Comment by azazellochg** [comment]
Fixed now in devel. Turns out eman2.91 has changed the run numbering. Now the first run is 0 not 1.

**Comment by pconesa** [comment]
Thanks!

**Comment by pconesa** [comment]
Still there is something weird in the builldbot worker:
![image](https://user-images.githubusercontent.com/785633/111125378-da961680-8571-11eb-800d-270e596665be.png)
On the left, my local machine (test passes), on the right, buildbot (test fails due to missing file) And is true. File is missing, but mean step does not fail.

I keep looking.

**Comment by pconesa** [comment]
Command is exactly the same:
/home/buildbot/devel/scipion/software/em/eman-2.91/bin/e2refine2d.py   --input=sets/inputSet__ctf_flip.lst --ncls=5 --iter=2 --nbasisfp=3 --naliref=5 --classkeep=0.800000 --classiter=2  --classaverager=ctf.weight.autofilt --normproj --fastseed --simcmp=ccc --simalign=rotate_translate_tree --classnormproc=normalize.edgemean --classcmp=ccc --classalign=rotate_translate_tree:flip=0 --center=xform.center --classaligncmp=ccc --classraligncmp=ccc --parallel=thread:4
/home/pablo/software/scipion/software/em/eman-2.91/bin/e2refine2d.py   --input=sets/inputSet__ctf_flip.lst --ncls=5 --iter=2 --nbasisfp=3 --naliref=5 --classkeep=0.800000 --classiter=2  --classaverager=ctf.weight.autofilt --normproj --fastseed --simcmp=ccc --simalign=rotate_translate_tree --classnormproc=normalize.edgemean --classcmp=ccc --classalign=rotate_translate_tree:flip=0 --center=xform.center --classaligncmp=ccc --classraligncmp=ccc --parallel=thread:4

**Comment by pconesa** [comment]
With a manual "fresh" installation and manual run of eman (devel) test is passing. 

Now I'm returning it through buildbot.

**Comment by pconesa** [comment]
It has passed: http://scipion-test.cnb.csic.es:9980/#/builders/73/builds/23
All I've done was to "clean" the previous installation.

**Comment by azazellochg** [comment]
Thank you @pconesa for sorting this out!
